### ISSUE TITLE
Shape-colors

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#141]
If shape=water, colors are not updated
![image](https://user-images.githubusercontent.com/78302632/127275127-c58445f1-b940-4f06-b70c-654607fd11db.png)
![image](https://user-images.githubusercontent.com/78302632/127275165-eabb739c-d5f3-443f-b54f-7a56f69e10cc.png)
Same for shape=CO2
![image](https://user-images.githubusercontent.com/78302632/127275289-14700e4e-9019-47c5-a2a6-c024de102f51.png)
 For A2 it works well

**Comment by Ron-Teller** [comment]
Currently, the colors are set according to atom types, and not individual atoms.

For example, if the ball shape is set to H2O, then there are 2 types of atoms, H and O. So both atoms of O will be colored according to the second color block, as such:
![image](https://user-images.githubusercontent.com/12688282/127416684-ab8e830b-f771-4ad7-9db8-258f1c4f083a.png)


If we want to enable coloring of individual atoms of the same type, this is certainly possible, but it might become cumbersome for the user, since defining colors for molecule of type CH4 will require 5 different size blocks and 5 different color blocks.
Currently, defining colors ford CH4 atom will look like this:
![image](https://user-images.githubusercontent.com/12688282/127416830-fed99b30-d3bd-4b97-b0a7-d833664f21ad.png)

However, if coloring individual atoms is allowed, then it will require many color and size blocks to be defined:
![image](https://user-images.githubusercontent.com/12688282/127416957-95b3e12d-f9ea-46fd-8283-d21955baf14b.png)

A solution to this would be to enable both options. If a user wants to color individual atoms then he can do so. If there is no color defined for a specific atom, then the previous color set for the same atom type will be set. If so color is set for an atom, then a default value (gray) will be chosen.

**Comment by Asnat-Zohar** [comment]
הפתרון הראשון שלך נראה לי מעולה.
 אבל לפי ההיגיון הזה, אם אני מגדירה צורה של מולקולה שבה יש שני אטומים זהים אז גם פה מבקשת לעשות שנגדיר אותם פעם אחת
