### ISSUE TITLE
Erase balls buttons

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#37]
Two issues relating the two erase balls buttons:

1. When click on them, they appear with a frame. Not consistent with other selected buttons' appearance.
![image](https://user-images.githubusercontent.com/78302632/109411709-a97fe880-79ac-11eb-99f2-d8ccc718232f.png)
Should be dark blue, such as 
![image](https://user-images.githubusercontent.com/78302632/109411720-b997c800-79ac-11eb-83e8-6104f9c8958a.png)

2. After activated the buttons cannot be released. Second click should release them.

@Ron-Teller

**Comment by Ron-Teller** [comment]
It has to be done this way, since the code to draw with a brush must be executed every turn (a turn in not a tick!) in netlogo. The "ציור ריבוע" and all other brush buttons are forever buttons, and they run code that activates the brush every turn, since drawing with a brush is interactive (brush cursor gets new position, shape size is chaged etc...).
A forever button keeps running, which is why it remains pressed down and blue, until it is clicked again.
The button "מחיקת כדורים" runs only once, it is not a forever button, which is why it does not remain pressed down and blue.

**Comment by Asnat-Zohar** [comment]
הכפתורים שמקבלים מסגרת נשארים לחוצים, לא משתחררים
