### ISSUE TITLE
If Run then do not allow to change colors

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#67]
במצב של כדורים עם תכונות מסוימות, צהובים שנעים למעלה: הוספתי כדורים עם תכונות אחרות, אדומים שנעים שמאלה. בהרצה 
הכדורים הצהובים נצבעו לאדומים, המשיכו לנוע אקראי בעוד הכדורים האדומים החדשים נעו שמאלה.

הצבע של הכדורים הישנים לא צריך להשתנות במהלך הריצה, כמו שהמהירות שלהם לא משתנה. 

שרונה: לוודא שצריך לקמפל בכל שינוי בקוד. כרגע אין קימפול אחרי שינוי הצבע
לבדוק את כל התכונות ואת כל הבלוקים

@Ron-Teller

**Comment by Ron-Teller** [comment]
it was originally designed like this to make the model more "responsive", so that users can change colors of existing balls while the model is running.
Also, we need to consider that it might be confusing if there are 2 populations, but 3 different colors of balls. The point of having populations is that all balls of that population share the same properties, but if we allow the same population to have different properties such as colors then it might become confusing. If there is a need for different colored balls, then it might be more appropriate to create another population (block space) instead of allowing balls of a single population to have different properties. 
How will the user know what population a ball belongs to if there are 3 colors and 2 populations?

**Comment by Asnat-Zohar** [comment]
מהתשובה שלך גם הבנתי שזה ממש מבלבל אם משנים את צבע הכדורים במהלך ריצה. יש לחסום את האפשרות לשינוי תכונות הכדורים במהלך ריצה. זה לא הגיוני ולא ברור

**Comment by Asnat-Zohar** [comment]
עכשיו לא משנה צבע בכלל. התחלתי עם צבע אפור (כמו שדיברנו) אבל אם משנה צבע אין אפשרות לעשות קומפילציה והצבע לא משתנה, לא בריצה ולא בכלל

**Comment by Ron-Teller** [comment]
Opened new issue as #76

**Comment by Asnat-Zohar** [comment]
עכשיו יש תיאום אבל אמרנו שבמשך הריצה הצבע לא יכול להשתנות והוא כן משתנה. צריך לא לאפשר שינוי במשך הריצה. וגם לא לאפשר לשנות את התפריט צבע כדי לשמור על תיאום בין מה שכתוב בבלוק ומה שרואים.
